### ISSUE TITLE
Decide whether to turn on -Wshadow on CI builds

### ISSUE THREAD

**Issue by fbbdev** [fbbdev/plot#12]
@hjmjohnson I'm seeking your advice here.

After merging #8 and [a small fix](https://github.com/fbbdev/plot/commit/4993509e0cfb01d61b9199c7e42af0ab47e79ecb) in class `TerminalInfo`, all -Wshadow warning are gone in clang. Gcc is still complaining, though, and it's being a bit too pedantic IMHO.

Clang seems to accept member shadowing at least in struct constructors (like `Color`), and this makes sense to me. Moreover, gcc complains about many cases like this:

```c++
BrailleCanvas& rect(Color const& stroke, Color const& fill, Rect rect, TerminalOp op = TerminalOp::Over)
```
Where argument `rect` would shadow the method. I don't think there could be confusion here and I believe it's a pretty common case. It seems I'm not alone (see [[1]](http://stackoverflow.com/questions/2958457/gcc-wshadow-is-too-strict) and [[2]](https://lkml.org/lkml/2006/11/28/253)). Clang 3.9 takes it without complaints.

So the question is: should I fix those errors and enable shadow warnings on continuous integration builds, or leave the code as it is and keep building without -Wshadow? Or maybe switch CI build environment to clang?

**Comment by hjmjohnson** [comment]
@fbbdev 

You have presented perfectly reasonable goals.  Unfortunately, compilers are not always reasonable or consistent.

I can relay that on many other large open source projects squashing the -Wshadow warnings (even the pedantic warnings) is the choice we have taken so that we can achieve clean builds across many platforms while still leveraging the benefits of using agresssive compiler warnings.

===
I think it is important that the CI build environment use at least 2 different compilers (i.e. both gcc and clang).  Those compilers should be the minimium target audience that you want to support (i.e. gcc 4.4.1 to support default RHEL version 6 clients).

I hope this is helpful.

It is a pleasure working with you.

Hans

**Comment by fbbdev** [comment]
Fixed all warnings and turned on -Wshadow in CI builds. I still think GCC is _way_ too pedantic :smile:
